msg = [
["What can you tell me about Iggy's client?", "Detective", -1],
["Oh you mean the thief?", "Omar", -1],
["Well she hasn't been convicted yet...", "Detective", -1],
["I'm sorry, 'alleged thief'.", "Omar", -1],
["She is definitely suspicious if you ask me.", "Omar", -1],
["How so?", "Detective", -1],
["She's the only one here strong enough to strangle anyone in the first place.", "Omar", -1], 
["And she's a sailor!", "Omar", -1],
["She must deal with ropes all the time, so she would know exactly how to use it.", "Omar", -1],
["I mean could it be any more obvious?", "Omar", -1],
["You think she did it because she knows how to use a rope?", "Detective", -1],
["Sounds like a bit of a stretch.", "Detective", -1],
["I just mean that when you think about it, of any of us three, why would anyone but Carrie have or choose to use a rope?", "Omar", -1],
["You think I have that kind of thing just laying around our two bedroom apartment?", "Omar", -1],
["Okay I guess point taken.", "Detective", -1],
["(But that does also make me wonder,)", "Detective", -1],
["(if Carrie knew the murder weapon would so obviously point to her, why would she leave it laying around?)", "Detective", -1],
["(I guess she could have panicked or run out of time?)", "Detective", -1],
["(It's something to think about.)", "Detective", -1]
]