/// @description Insert description here
// You can write your code in this editor
msg = [
["So you're here about Iggy, huh?", "Carrie", -1],
["Can I ask who you are?", "Detective", -1],
["My name is Carrie.", "Carrie", -1],
["Iggy was defending me.", "Carrie", -1],
["Defending you?", "Detective", -1],
["Oh that's right! Omar mentioned something like that.", "Detective", -1],
["Are you being charged with a crime?", "Detective", -1],
["Piracy.", "Carrie", -1],
["Piracy?", "Detective", -1],
["Like downloading mp3's off of Napster?", "Detective", -1],
["I wouldn't think the courts would bother with something like that.", "Detective", -1],
["No, ship piracy.", "Carrie", -1],
["I'm a sailor.", "Carrie", -1],
["And this probably goes without saying, but I'm innocent.", "Carrie", -1],
["Of that crime or this one?", "Detective", -1],
["Both.", "Carrie", -1],
["(Well I guess we'll see about that.)", "Detective", -1],
["(Thank god about Napster though.)", "Detective", -1],
["(Entire discography of Phil Collins, you're safe on my hard drive.)", "Detective", -1],
["Um, excuse me.", "Herby", -1],
["Are you a detective?", "Herby", -1],
["(*I can feel it com-ing in the air to-night*)", "Detective", -1],
["Oh, what?", "Detective", -1],
["Ahem!", "Detective", -1],
["Yes!", "Detective", -1],
["That's me, I am a professional...detective.", "Detective", -1],
["I'm Iggy and Omar's neighbor, Herby.", "Herby", -1],
["I came over when I heard the commotion.", "Herby", -1],
["Is it really true?", "Herby", -1],
["Is Iggy dead?", "Herby", -1],
["I haven't had a chance to see the body for myself yet,", "Detective", -1],
["but I'm very sorry for your loss.", "Detective", -1],
["*sniffle* I appreciate that.", "Herby", -1],
["Iggy and I were very close.", "Herby", -1],
["Of course.", "Detective", -1],
["(Well, first things first.)", "Detective", -1],
["(I need to take a look at the crime scene before I can draw any conclusions about the case.)", "Detective", -1],
["Do you know where I might find the body?", "Detective", -1],
["He's in the den over there.", "Herby", -1],
["Thank you.", "Detective", -1],
["Don't worry, I'll solve this case lickety split.", "Detective", -1],
["(I think the living room is this way.)", "Detective", -1]
]