msg = [
["Do you know anything about this?", "Detective", -1],
["What's that, some kind of note?", "Herby", -1],
["I found this in the trash at the crime scene,", "Detective", -1],
["but I'm not sure if it's related to the case.", "Detective", -1],
["It could just be random garbage,", "Detective", -1],
["but I'm kind of hoping it's something more.", "Detective", -1],
["Does this message mean anything to you?", "Detective", -1],
["'I left a surprise for you in the den. You're Welcome!'", "Detective", -1],
["A surprise in the den?", "Herby", -1],
["I guess it could've been any number of things not necessarily related to the case.", "Herby", -1],
["Aw darn.", "Detective", -1],
["But maybe it could be related!", "Herby", -1],
["Like what if Carrie left that note for Iggy to lure him into the den so she could strangle him?", "Herby", -1],
["I mean since he's gone now, so are her money problems!", "Herby", -1],
["Though I guess she still needs a new lawyer.", "Herby", -1],
["So you really think that Carrie did it?", "Detective", -1],
["I mean, I have no way of understanding what would drive someone to do something so awful.", "Herby", -1],
["But money seems like a pretty decent motivator.", "Herby", -1],
["Who can say with certainty?", "Herby", -1],
["(The evidence can.)", "Detective", -1],
["(If I can just figure out what it all means.)", "Detective", -1]
]