//this belongs to the option tree:
//show us the fish
//go bring it to her
//save me a piece
msg = [
["Show us the fish!", "Detective", -1],
["What?", "Herby", -1],
["If you haven't gotten the chance to give her the fish yet because of the murder,", "Detective", -1],
["then you should still have it, right?", "Detective", -1],
["Go get it.", "Detective", -1],
["Uh........", "Herby", -1],
["Go on,", "Detective", -1],
["get out of here you crazy cook!", "Detective", -1],
["Show us the fish.", "Detective", -1],
[".................", "Herby", -1],
["Come on, I'm starving!", "Detective", -1],
["What are you waiting for?", "Detective", -1],
[".......................", "Herby", -1],
[".................................", "Herby", -1],
[".............................................", "Herby", -1],
["You don't have it, do you?", "Detective", -1],
["Because you couldn't have it.", "Detective", -1],
["Because Iggy ate it!", "Detective", -1],
["Because you poisoned him!!!", "Detective", -1],
["FINE!", "Herby", -1],
["I DID IT!", "Herby", -1],
["I POISONED IGGY!", "Herby", -1],
["!", "Carrie", -1],
["!", "Omar", -1],
["I'm sorry, what was that?", "Detective", -1],
["I killed him!!", "Herby", -1],
["That nosy, rotten little jerk had it coming!", "Herby", -1],
["This wouldn't have happened if he could've just learned to mind his own business!", "Herby", -1],
["What are you talking about?!", "Omar", -1],
["How dare you?!", "Omar", -1],
["Iggy found out I was stealing money from HerbyRealT,", "Herby", -1],
["and he said he was gonna turn me in!", "Herby", -1],
["He said it was 'the right thing to do'.", "Herby", -1],
["But it's my company!", "Herby", -1],
["And my business!!", "Herby", -1],
["And he should've left me ALONE!!!", "Herby", -1],
["So I shut him up.", "Herby", -1],
["Now that little do-gooder can mind his own business forever.", "Herby", -1],
["That's enough HerbyT!", "Detective", -1],
["It's over.", "Detective", -1],
["You can tell it to the judge.", "Detective", -1],
["...", "Omar", -1],
["I have to go now,", "Detective", -1],
["but I'm very sorry for your loss.", "Detective", -1],
["Thank you for solving the case.", "Omar", -1],
["I hope that Iggy can rest in peace now.", "Omar", -1],
["Of course, I do too.", "Detective", -1],
["And Carrie, good luck with your trial.", "Detective", -1],
["'Appreciate it.", "Carrie", -1],
["Good luck with detecting, or whatever!", "Carrie", -1],
["I'll do my best.", "Detective", -1],
["Now then, on to the next case!", "Detective", -1]
]
//THIS IS THE END OF THE GAME