//this is for when you click on omar in scene four
msg = [
["So Omar, I hear things have been pretty tense between you and Iggy lately.", "Detective", -1],
["Who told you that?", "Omar", -1], 
["Popeye the Pirate over there?", "Omar", -1],
["Typical.", "Omar", -1],
["Like she would know anything about what's going on with us.", "Omar", -1],
["Why would you trust a criminal's claims anyway?", "Omar", -1],
["I don't really think it's right to disregard her just because she's suspected of a crime.", "Detective", -1],
["And you're kind of in the same boat as her right now,", "Detective", -1],
["no pun intended.", "Detective", -1],
["What, you suspect me?!", "Omar", -1],
["How dare you? I called you here!", "Omar", -1],
["Why would I call you to the scene of my own crime?!", "Omar", -1],
["I'm not saying you did it for sure,", "Detective", -1],
["I just want to know what you and Iggy were fighting about.", "Detective", -1],
["That's all.", "Detective", -1],
["Maybe what you say will clear my suspicion.", "Detective", -1],
["You're pretty sneaky, huh?", "Omar", -1],
["Fine.", "Omar", -1],
["Yeah, we were 'fighting'.", "Omar", -1],
["And it's all Carrie's fault FYI.", "Omar", -1],
["Carrie's fault?", "Detective", -1],
["Not only am I subjected to living with a criminal in my home,", "Omar", -1],
["but she hasn't paid Iggy a cent!", "Omar", -1],
["Do you know what that means for me?", "Omar", -1],
["I've had to cover his half of the rent for the past two months!", "Omar", -1],
["I was just frustrated with him.", "Omar", -1],
["He always goes too far, and gets too involved in his cases,", "Omar", -1],
["I'm the one who gets inconvenienced!", "Omar", -1],
["Now he's gone, and the last time we spoke I was yelling at him about it...", "Omar", -1],
["He really was a good person.", "Omar", -1],
["He sacrificed a lot for his clients,", "Omar", -1],
["and I guess I didn't really appreciate what that meant until now.", "Omar", -1],
["I wish I'd told him that then.", "Omar", -1],
["I'm sure he knew how you felt.", "Detective", -1],
["Maybe you can make up for it by being nicer to Carrie?", "Detective", -1],
["I mean if Iggy was willing to give her the benefit of the doubt,", "Detective", -1],
["maybe you can too.", "Detective", -1],
["Maybe she's innocent of piracy, but what about Iggy's murder?", "Omar", -1],
["Is this your way of saying you don't suspect her at all?", "Omar", -1],
["Not necessarily.", "Detective", -1],
["I just don't like to jump to conclusions,", "Detective", -1],
["or treat people like they're guilty before I know it for sure.", "Detective", -1],
["But it's my job to consider all the possibilities,", "Detective", -1],
["so I'll get to the bottom of this soon enough.", "Detective", -1]
]