//this is for when you ask herby about iggy
msg = [
["Could you tell me a little about Iggy?", "Detective", -1],
["Iggy?!", "Herby", -1],
["I loved that guy!", "Herby", -1],
["He was so compassionate, always trying to help people out.", "Herby", -1],
["Man, I'm really gonna miss him.", "Herby", -1],
["So you don't think anyone would have a reason to dislike Iggy?", "Detective", -1],
["Iggy?", "Herby", -1],
["Iggy!", "Herby", -1],
["No way!", "Herby", -1],
["He was like Superman...or Batman...or Spiderman!", "Herby", -1],
["He was just um...", "Herby", -1],
["The man?", "Detective", -1],
["Yes!", "Herby", -1],
["He was the MAN!", "Herby", -1],
["Always getting involved with other people and fixing their problems.", "Herby", -1],
["He was my hero.", "Herby", -1],
["...", "Herby", -1],
["I can't believe someone's done this to him.", "Herby", -1],
["Was Iggy acting strangely at all before this happened?", "Detective", -1],
["Now that you mention it,", "Herby", -1],
["Iggy did seem really stressed out as of late.", "Herby", -1],
["Stressed?", "Detective", -1],
["What for?", "Detective", -1],
["Well I think it has something to do with his client.", "Herby", -1],
["Carrie I think was her name?", "Herby", -1]
]